"""add_booking_messages

Revision ID: 1bd9a97bb41c
Revises: 2a37754db766
Create Date: 2026-03-16 10:34:49.877092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd9a97bb41c'
down_revision: Union[str, None] = '2a37754db766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('sender_user_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_messages_booking_id'), 'booking_messages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_messages_sender_user_id'), 'booking_messages', ['sender_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_messages_sender_user_id'), table_name='booking_messages')
    op.drop_index(op.f('ix_booking_messages_booking_id'), table_name='booking_messages')
    op.drop_table('booking_messages')
    # ### end Alembic commands ###
