"""add_availability_blocks

Revision ID: 2a37754db766
Revises: a039e36fa9f2
Create Date: 2026-03-16 09:54:36.059147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a37754db766'
down_revision: Union[str, None] = 'a039e36fa9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dj_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('block_type', sa.Enum('MANUAL', 'BOOKING', 'GOOGLE_CALENDAR', name='availabilityblocktype'), nullable=False),
    sa.Column('source_booking_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dj_id'], ['dj_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_blocks_dj_id'), 'availability_blocks', ['dj_id'], unique=False)
    op.create_index(op.f('ix_availability_blocks_end_time'), 'availability_blocks', ['end_time'], unique=False)
    op.create_index(op.f('ix_availability_blocks_start_time'), 'availability_blocks', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_blocks_start_time'), table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_end_time'), table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_dj_id'), table_name='availability_blocks')
    op.drop_table('availability_blocks')
    # ### end Alembic commands ###
